name: parking_map
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_naver_map: ^1.2.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  speech_to_text: ^6.6.1
  permission_handler: ^11.3.0
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  




flutter:
  assets:
    - assets/parking_info.json
  uses-material-design: true

